---
title: Integrating Earth Observation Data into Life Cycle Assessment
subtitle: Project proposal for a Case Study on quantifying Albedo Change from Photovoltaic Systems
author: Elke Michlmayr
format:
  html:
    code-fold: true
  pdf:
    number-sections: true
    include-in-header: titlepage.tex
    keep-tex: true
    mainfont: "Georgia"
    sansfont: "Helvetica"
    monofont: "Courier New"
execute:
  warning: false
  message: false
lang: en
bibliography: bibliography.bib
csl: apa-no-ampersand.csl
---

```{=latex}
\section*{Abstract}
Remote sensing, in particular satellite-based earth observation (EO), provides extensive datasets that hold potential for supporting life cycle assessments (LCAs) to evaluate environmental impacts across a product or service life cycle. This project work performs a case study for integrating remote sensing data in LCA to determine if and how observational satellite data can be integrated into LCA to enhance the accuracy of environmental impact evaluations in various stages, especially in the inventory and modeling phases. 

A promising area where such data might be applied is for the evaluation of changes in surface reflectivity (albedo) associated with the installation of photovoltaic panels (PV). This can be assessed from the relevant satellite data before and after the installation of the PV sites under study, for both building mounted PV panels and open ground PV installations in deserts, on grasslands, on croplands, or on water surfaces. Depending on the type of land cover there might be net positive, neutral, or net negative effects. For most cases, net positive effects are expected. The change in surface albedo caused by replacing natural or built surfaces with PV panels is expected to represent a significantly smaller environmental impact compared to the environmental benefits of solar power over non-renewable energy sources. However, it constitutes a measurable effect that can potentially be quantified and incorporated into LCAs. 

The structure of the project work is as follows. Following the introduction, a review of existing literature on the incorporation of albedo changes into LCA, as well as the use of remote sensing based metrics to support this integration, will be presented. The central contribution of the work will be the design of a detailed research project plan including methodological steps, project milestones, and a time plan. For the interested reader, the appendix provides introductory overviews of life cycle assessment and satellite-based earth observation for readers seeking background information on these topics.

Grading consists of the following parts: Scientific Publication: 50\%, Supporting Material 15\%, Oral Presentation 25\%, Work Process / Project Management: 10\%
```

# Introduction

Life Cycle Assessment (LCA) as defined in [@ISO14040] and [@ISO14044] is a standardized tool used to evaluate the environmental impacts associated with every stage of a product or service's life, from raw material extraction through production, use, and disposal. Central to the accuracy and usefulness of an LCA is the availability and quality of the underlying data. Without robust and representative data, the conclusions drawn from an LCA risk being misleading or incomplete. LCA methodologies often rely on aggregated impact factors, which can be globalized or regionalized. High spatial variability intrinsic to environmental phenomena can not be captured with this approach. 

Remote sensing, particularly through satellites, provides vast amounts of data. Satellites offer a unique, large-scale perspective for continuous observation of the earth's surface and atmosphere. They collect data that can be directly or indirectly used to assess land cover, vegetation health, surface temperatures, atmospheric gases, and ocean characteristics. All of these are essential for understanding environmental trends and changes over time. Satellite derived earth observation (EO) data is continuously collected and supports a wide range of applications, from climate modeling and disaster response to agricultural planning. In particular, EO data allows (1) to assess if a certain location is currently covered by a solar panel, and (2) measure the reflectivity in that location before and after the installation. 

Albedo is the ratio of solar energy reflected by a surface. Light surfaces (e.g. snow and ice) reflect a large portion of the sunlight while dark surfaces like asphalt do not reflect it but instead absorb the sunlight and convert it into heat. Therefore, when the albedo of the earth’s surface or atmosphere changes, the planet’s energy balance is altered. The planetary boundaries framework @richardson2023earth lists surface albedo changes after greenhouse gases and aerosols as the third key anthropogenic driver in the climate change category, which is measured in (1) atmospheric CO₂ concentration and (2) energy imbalance at the top of the atmosphere. The change in the balance between incoming and outgoing energy is known as radiative forcing (RF). This effect drives weather patterns, surface temperatures, and consequently, the climate system.  

Solar panels convert sunlight into both electrical energy and heat. Since PV installations typically replace existing surfaces with lower-albedo PV modules, they alter the surface reflectivity and, consequently, the local and global energy balance. Today's solar panels are all in the typical dark color. Architects like to use other lighter colors, especially for facade installations. This is realised by installing lighter colored glass panels in front of the solar panel, which reduces their efficiency. Efforts to improve the performance of colored panels, such as those described by @ji2019vivid, are ongoing and will take time to reach practical application. 

The aim of this work is to devise a project plan to (1) quantify the impact of albedo changes associated with dark-colored PV installations and to (2) integrate this effect into life cycle assessments (LCAs) of photovoltaic systems. While ISO14040 [@ISO14040] provides the necessary structure for an LCA, it refrains from dictating specific methodological approaches for emerging or complex environmental phenomena, such as the albedo effect and radiative forcing. This absence of prescriptive methods allows for the integration of additional data sources, e.g EO data, in LCAs.

# Literature study

Several research areas relate to this topic, including albedo effects in general, albedo effects of photovoltaic (PV) systems, the inclusion of albedo effects in life cycle assessment (LCA), and remote sensing applications for location-specific LCAs. This chapter provides an overview of existing studies in these fields that are relevant to the present work.

## Albedo effects compared between surfaces and on the hemisphere level

@susca2012enhancement proposed an enhancement of the LCA methodology with a time-dependent climatological model for including the effect of surface albedo on climate. They evaluated their theoretical findings with a case study of a black and a white roof evaluated over the timeframes of 50 and 100 years. The comparative LCA of the two roofs showed that the high surface albedo of the white roof played a crucial role in offsetting RF.

@hasler2024accounting find that maximizing the climate benefits of tree cover restoration requires accounting for albedo effects since they often offset or even reverse carbon removal gains, especially in dryland and boreal regions. Using spatial data, the study shows that while many restoration projects target  climate-positive areas, many face an albedo offset of at least 20%. The study suggests rolling out large-scale tools to identify where restoration delivers true net climate benefits.

@zhu2024changes indicate the significant impacts of climate change and human disturbances on East Asia grassland ecosystems from the perspective of altered albedo. Changes in vegetation greenness and soil properties have a substantial impact on albedo.

@wu2024satellite estimate a 30-m-resolution annual surface albedo dataset for more than 3000 large cities  worldwide for the period from 1986 to 2020 from the Landsat surface reflectance product (see @usgs_landsat_sr) and find an overall decreasing trend of albedo during the 35-year evaluation period, which is robust accounting for uncertainties from training sample representativeness, data uncertainty, seasonal variation, and snow-cover contamination.

@loeb2025emerging use 24 years of satellite observations to show that there is a small measurable difference between the Northern and Southern Hemispheres in both absorbed solar radiation (ASR) and outgoing longwave radiation (OLR). The emerging darkening of the Northern Hemisphere relative to the Southern Hemisphere is linked to changes in aerosol radiation interactions, surface albedo, and water vapor distributions. This hemispheric asymmetry in radiation is closely connected to variations in the atmosphere and ocean general circulation.  The assumption so far was that changes in cloud cover would balance the differences between the hemispheres (see @datseris2021earth), but this study suggests that this compensating effect is not completely effective. Understanding how the clouds respond to the developing imbalance is critical for predicting future climate evolution. @diamond2024testing follow up on this line of research by decomposing the hemispheric albedo symmetry into components associated with the surface, clear-sky atmosphere, and different cloud types as defined by cloud effective pressure and optical thickness. 

## PV installations and albedo effects

One of the earliest studies examining the environmental impacts of photovoltaic (PV) installations is @fthenakis2008emissions, and since then, numerous scientific publications have investigated PV systems through LCA approaches. While most of them overlook the effects of surface albedo change, such as @gerbinet2014life, @ferrara2024life, @gomez2024agile, a limited number of studies have attempted to quantify the effect in a way that could be used as in input to an LCA:

*   @nemet2009net estimated the effects of covering the earth with sunlight-absorbing panels on a large scale and therefore reducing surface albedo. They found that avoided emissions from PV generated energy were far greater than the observed warming effect from the related albedo reduction. 

*   @wei2024small confirmed these results based on global satellite data, and also showed that albedo-induced positive radiative forcing can be offset by negative radiative forcing from clean solar generation in most PV farms within one year.

*  @xu2024global performed a global assessment of the effects of solar farms on albedo and vegetation for 116 large solar farms using MODIS data. They demonstrated that the installation of these farms decreased the annual mean surface shortwave albedo and reduced the enhanced vegetation index (EVI) relative to the surrounding areas. The greatest impacts on albedo were observed in barren land, followed by grassland and cropland, while the opposite order applied for vegetation impact. In terms of seasonal and latitudinal variations, the largest impact on albedo was observed at high latitudes in winter. 

Several related aspects are worth mentioning:

*  @gul2018enhancement examine the effects of the surfaces around PV installation and find that these have a small effects on the performance. It is preferrable to use bright, reflective materials like white tiles around PV panel since these maintain higher and more stable albedo values, especially in cloudy northern regions where ground reflection contributes significantly to total solar gain.

*  @coimbra2025energy focus on thermal effects of solar plants on the environment and vice-versa. Large-scale solar power plants are often built in arid or desert habitats with fauna and flora that are highly sensitive to changes in temperature and humidity. Many factors such as wind direction and speed, dust concentration, ground condition, panel configuration density, orientation and distribution throughout the solar field, all affect the local environment, the balance between radiation and convection, and in turn, the performance and thermal impact of solar power plants. 

* @barron2016photovoltaic investigated the same topic and found that PV farms induce a “heat island” effect when lowering the terrestrial albedo from ~20% in natural deserts to ~5% over PV panels by installing a PV farm. Temperatures were regularly 3–4 °C warmer than the surrounding wildlands at night.

## Albedo effects of PV installations per original surface

Other studies investigated the impact of PV on radiative forcing at several different installation sites such as city roofs, deserts, alpine locations, and lakes:

*  @zhou2025assessing used a LiDAR-based approach to quantify urban albedo for the city of Delft assuming that all appropriate roofs would be covered with PV panels and found that this would yield 485.72 GWh of electric energy per year, while it would minimally lower the city’s albedo and impose $3.53 * 10^{-8}W m^{-2}$ positive RF. The results were validated using MODIS satellite observations. 

*  @li2022comparative examined the effects of PV panels on surface radiation through a comparative study between a PV site and a reference site in the Gobi area of Xinjiang, China in summer 2020. The results showed that nighttime outgoing longwave radiation (OLR) was lower at the PV site, while daytime values were similar. The PV site’s surface albedo (0.14) was 39.1% lower than the reference site’s (0.23). Overall, net radiation was 30.7% higher at the PV site: 75% due to reduced upward shortwave radiation, and 25% to lower nocturnal longwave radiation.

*  @wang2025environmental studies PV installations in an alpine meadow on the eastern Tibetan Plateau and found an increased net radiation, by 28.9%, but reduced albedo and wind speed, by 31.6% and 36.2%. Air temperature rose in daytime and summer, but dropped at night and in winter. Soil under panels was colder and drier, while gaps were colder and wetter, extending the frozen period by roughly 50 days and slowing moisture loss up to 3.5×. These shifts alter local energy and water balances and may moderate climate warming impacts, warranting longer-term studies to evaluate the long-term impacts on vegetation dynamics and permafrost processes.

*  @li2022physical examined fishery complementary PV plants using a physical model to reveal their microclimatic effects. Deployment turned the lake into a heat sink, reducing albedo by 18.8%. Water energy change was driven by an water/air vapor pressure deficit. Also, the panels warmed the surrounding environment, with heating intensity depending on water depth and strongest at the surface.

In conclusion, impacts on albedo caused by PV installations were observed on all these surfaces, and these impacts could potentially be included in an LCA.

## Albedo effects of the surroundings of PV installations

Some studies looked at the Albedo effects of the surroundings of PV installations:

*  @cosgun2024investigating explored the performance of floating PV modules installed over water surfaces, focusing on their efficiency and environmental benefits. A 1 MW PV system was simulated with two types of PV modules, bifacial and monofacial, both mounted 1 meter above the water. Results showed that bifacial modules generated more energy annually than monofacial ones due to enhanced albedo reflection from the water surface.

*  @lavaert2023influence investigated how different ground cloths affect the electricity production of two agrivoltaic systems: fixed vertical bifacial panels and horizontal single-axis trackers. The study aimed to determine whether reflective ground covers, such as white cloths, could enhance light capture and energy generation. Simulations suggested that the white ground cloth could increase the incident irradiance on the vertical bifacial panels by about 8%, but real-world measurements over 5.5 months showed no significant difference between ground covers. In contrast, for the horizontal single-axis tracker system, there was a clear benefit with the white ground cloth leading to higher yields.

## Albedo effects in LCAs

Several studies from the LCA research community have attempted to quantify albedo-related effects for inclusion in LCAs: 

*  @david2025 assessed whether accounting for surface albedo change caused by land use change in carbon credit quantification methods influences the amount of credits and found that overcrediting can happen because planting trees can darken the land.

*  @jungbluth2012life presents collected data on the albedo effects from various surfaces including PV panels. While the direct impact on global radiative forcing is considered minimal, local albedo changes induced by large PV installations could have minor implications for nearby ecosystems and microclimates. 

*  @bright2012climate examines two key dynamic factors affecting bioenergy’s climate impact: temporary changes in the terrestrial carbon cycle, and land surface albedo. The paper proposes ways to integrate these factors into LCA. Using a case study of transportation biofuel from managed boreal forests in northern Europe, the authors develop global warming potential (GWP) indices for different land management scenarios, highlighting the need for region-specific characterization factors and discussing related uncertainties.

*  @cai2016consideration quantified land use change (LUC) induced albedo effects from large-scale U.S. biofuel production and compared them with greenhouse gas emissions from traditional life-cycle analyses. Using over 1.4 million satellite albedo observations across six Agro-Ecological Zones, paired with high-resolution crop data, they modeled radiative forcing related impacts of LUC for seven crop types. Results show average albedo effects of −1.8 g CO₂e/MJ for corn ethanol (cooling), +2.7 g CO₂e/MJ for miscanthus, and +12.1 g CO₂e/MJ for switchgrass (warming). Strong spatial variability indicates that biofuel climate impacts depend heavily on local land and vegetation characteristics.

## Spatially explicit LCAs

Spatially explicit LCAs are a refinement of traditional LCAs to incorporate geographical and location-specific information into the assessment of environmental impacts. The key difference is the use of location-specific inventory data for different purposes, such as road infrastructure planning as described by @karlsson2017. Geographic Information Systems (GIS) and remote sensing are often used to map and quantify regional effects. 

@li2021spatializing provide a meta study of 105 publications on GIS-based LCAs and propose a universal methodology framework to address the following issues: (1) setting up a geographically referenced system in the goal and scope definition phase; (2) spatializing life-cycle data and integrating and computing foreground and background data in the inventory analysis phase; (3) developing spatialized characterization factors with different requirements on resolution and data availability in the impact assessment phase; and (4) harmonizing the contribution analysis of different zones, unit processes, and elementary flows to visualize the spatialized environmental footprint in the interpretation phase.

@itten2023remote explored how remote sensing data from satellites can support and partly replace company-provided data for scope 3 reporting to improve transparency and enable comparisons. The interdisciplinary research group identified remote sensing data sources for agriculture, mining, and energy sectors. Commercial providers already offer relevant ESG-oriented remote sensing based data products based on processed satellite imagery. These datasets on land use change (most recently by @jian2025highly), biodiversity, and biomass carbon can enable regionalized and consistent LCI models across larger areas and time periods.

### Relevant datasets for surface albedo

@roccetti2024hamster provide a dataset for surface albedo based on the MODIS Surface Reflectance Black-Sky Albedo dataset (see @schaaf2021modis) and principal component analysis (PCA) as described by @hotelling1933pca.

@riihela2024four present CLARA-A3 surface albedo data as the third edition of the CM SAF cLoud, Albedo and surface Radiation (CLARA) data record family. The temporal coverage of this edition is extended from 1979 until the near-present day. The core algorithms and data format remain unchanged from previous editions, but now white- and blue-sky albedo estimates are also available for the first time in CLARA data.

## Accuracy of satellite-derived data

The accuracy of satellite-derived data is crucial. Many scientific publications are focused on assessing accuracy levels and understanding the reasons for discrepancies:

*   @gruber2020validation propose good practice guidelines for the validation of global coarse-scale satellite soil moisture datasets and practical recommendations on data preprocessing and presentation of statistical results together with a recommended validation protocol and an example validation.

*   @langsdale2025challenges review key challenges in validating satellite ECVs across terrestrial, oceanic, and atmospheric domains. They focus on issues with reference data, their use in validation, and comparison methods and provide recommendations for improving uncertainty modeling, transparency about data limitations, metadata management, and best practices for validation methodologies.

*   @paris2023accuracy discuss issues caused by inconsistencies between the actual data and the information derived from satellite data that can be attributed to factors such as differences in viewpoint perspectives, i.e., aerial versus ground views, or spatial resolution of the satellite images versus the extent of the land cover (LC) present in the scene. 

*   @tran2023uncertainty reviewed 676 papers (2011–2021) on uncertainty assessment of remote sensing-based evapotranspiration (RS-ET), categorizing them by methods, context, and reporting metrics. They found that assessments are inconsistent in methodology, reference data, geographic coverage, and uncertainty reporting. The study recommends that future work should clearly document validation context, reference data uncertainties, spatial and temporal mismatches, and report multiple performance metrics.

*   @manninen2022cloud describes a new method for cloud-correcting observations of black-sky surface albedo derived using the Advanced Very High Resolution Radiometer (AVHRR). Cloud cover constitutes a major challenge for surface albedo estimation using AVHRR data for all possible conditions of cloud fraction and cloud type with any land cover type and solar zenith angle.

<!-- 
Groups:
https://en.wikipedia.org/wiki/Space_for_Climate_Observatory

Journals:
International Journal of Applied Earth Observation and Geoinformation

People:
Remote sensing agriculture: Bruno Basso
https://scholar.google.com/citations?user=EItklH0AAAAJ&hl=en

Problems:
Amazon often full with clouds, gets exploited by loggers

Use cases: 
forest https://scholar.google.com/scholar?hl=en&as_sdt=0,5&qsp=2&q=forest+loss+life+cycle+assessment&qst=bl
water (?) 
contrails (??)

## Environmental impact of satellites

(2024) A life cycle assessment study of European Space Agency's space tracking terminal
https://pubs.rsc.org/en/content/articlehtml/2024/va/d4va00070f

(2024) Life Cycle Assessment for Varying Design Lifetime Mission Architecture for Low Earth Orbit Constellation Satellites with Starlink as a Case Study
https://www.researchgate.net/publication/384634078_Life_Cycle_Assessment_for_Varying_Design_Lifetime_Mission_Architecture_for_Low_Earth_Orbit_Constellation_Satellites_with_Starlink_as_a_Case_Study

(2025) Greenhouse Gas (GHG) Emissions Poised to Rocket: Modeling the Environmental Impact of LEO Satellite Constellations
https://arxiv.org/abs/2504.15291

Quantifying the Environmental Impacts of Manufacturing Low Earth Orbit (LEO) Satellite Constellations 
https://www.mdpi.com/2071-1050/16/21/9431

Estimates for environmental impact of satellites:
https://pre-sustainability.com/customer-cases/environmental-impacts-satellite-mission/


# Tools and datasets

In the following, datasets and tools that could be valuable as input for LCAs are assessed.

## AlphaEarth Foundations

An embedding field model for accurate and efficient global mapping from sparse label data

https://deepmind.google/discover/blog/alphaearth-foundations-helps-map-our-planet-in-unprecedented-detail/

https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_SATELLITE_EMBEDDING_V1_ANNUAL?hl=de

@brown2025alphaearthfoundationsembeddingfield

10x10 meter

Unprecedented volumes of Earth observation data are continually collected around the world, but high-quality labels remain scarce given the effort required to make physical measurements and observations. This has led to considerable investment in bespoke modeling efforts translating sparse labels into maps. Here we introduce AlphaEarth Foundations, an embedding field model yielding a highly general, geospatial representation that assimilates spatial, temporal, and measurement contexts across multiple sources, enabling accurate and efficient production of maps and monitoring systems from local to global scales. The embeddings generated by AlphaEarth Foundations are the only to consistently outperform all previous featurization approaches tested on a diverse set of mapping evaluations without re-training. We will release a dataset of global, annual, analysis-ready embedding field layers from 2017 through 2024. 

https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_SATELLITE_EMBEDDING_V1_ANNUAL?hl=de#description
https://medium.com/google-earth/ai-powered-pixels-introducing-googles-satellite-embedding-dataset-31744c1f4650

## Planetary Computer

The Planetary Computer combines a multi-petabyte catalog of global environmental data with intuitive APIs, a flexible scientific environment that allows users to answer global questions about that data, and applications that put those answers in the hands of conservation stakeholders.

https://planetarycomputer.microsoft.com/

## GlobalBuildingAtlas

https://github.com/zhu-xlab/GlobalBuildingAtlas?tab=readme-ov-file

## Cropland Data Layer

Agriculture: The Cropland Data Layer (CDL) is a dataset provided by the U.S. Department of Agriculture's National Agricultural Statistics Service (NASS) that provides information about crop types across the United States.

## Forest baseline

(2025) Natural forests of the world-a 2020 baseline for deforestation and degradation monitoring @neumann2025natural 
Forest stuff PhD student: https://github.com/SherryJYC

## MethaneSAT

https://developers.google.com/earth-engine/datasets/catalog/projects_edf-methanesat-ee_assets_public-preview_L4area?hl=de

https://showcase.earthengine.app/view/methanesat

https://blog.google/outreach-initiatives/sustainability/how-satellites-algorithms-and-ai-can-help-map-and-trace-methane-sources/
-->

# Research questions {#sec-research-questions}

Three main research questions are explored: 

1.   How can satellite-derived remote sensing data be applied to assess changes in surface albedo resulting from PV installations by comparing its effects before and after the installation? What level of spatial and temporal data aggregation is required to obtain meaningful results, given the quality and resolution of the data? The hypothesis is that the inherent noise found in satellite-derived remote sensing data (e.g. due to varying weather conditions and cloud cover) along with its limited spatial resolution will represent major constraints to be dealt with. Nevertheless, it is expected that it will be possible to derive statistically significant result estimates with appropriate data processing and statistical methods.

1.   How does the original surface of PV systems, such as building or open ground, influence the amount of albedo change from the installation? Is it feasible to identify the original surface such as buildings, deserts, grasslands, croplands, water? Is it possible to assess and quantify the albedo change by original surface type? Furthermore, is seasonality (e.g., temporal snow cover and vegetation dynamics) a relevant factor? The hypothesis is that the impact will depend on the original surface being replaced. Albedo changes for building mounted PV panels are expected to be minor since the albedo of typical dark roofing is expected to be similar to that of a solar panel surface. However, for other surfaces such as deserts, the changes in albedo might be significant.

1.   How can the satellite-derived data be incorporated into LCAs in a methodologically sound and credible manner, enabling its authoritative use in environmental impact assessments of solar energy systems? The hypothesis is that satellite-derived datasets from sources such as U.S. National Oceanic and Atmospheric Administration (NOAA) or European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT) are considered reliable and scientifically validated. The expectation is that the given data quality should allow for quantifying aggregated albedo changes by original surface type and consequently support the incorporation of these effects into LCAs of photovoltaic systems.

<!--

* Plan some kind of LCA project based on Oil and Gas Infrastructure Mapping (OGIM) / MethaneSAT: https://developers.google.com/earth-engine/datasets/catalog/EDF_OGIM_current?hl=de (also see ESU-services: https://esu-services.ch/fileadmin/download/jungbluth-2022-oilgas-FSLCI-20220914.pdf) Fokus auf spezifische Commodity (Erdgas, Rohöl oder Fracking)

   * MethaneSAT data: https://portal.methanesat.org/en/emissions-map?view-latitude=29.97421&view-longitude=22.15457&view-zoom=3.48&date=2025-06-30&platform=MethaneSAT&product=l4&color-scale=msat_warm_default
   * https://www.methanesat.org/project-updates/new-methane-emissions-insights-will-continue-methanesat-data-catalogue-processed

* Plan some kind of LCA project based on AlphaEarth Foundations (could use data within Google Earth Engine for analysis and visualization for research or educational use. Downloading, redistributing, or incorporating the data into other software is not permitted.)
    * Landwirtschaft mit Fokus auf eine spezifische Commodity (Kaffee, Soja, Kakao, Reis, oder andere)
    * Mining mit Fokus auf spezifische Commodity (Kupfer, Gold, Nickel, Silber, Aluminium, Eisen, Kohle, Lithium, Uran)
    * Energiesektor mit Fokus auf spezifische Kraftwerke (Kohle, Gas, Wasserkraft, Windkraft oder PV)
    
* Plan a project to use ESA Biomass satellite for LCA for forest loss (data not yet in the public domain)

* LCA to assess the environmental impact of satellites in comparison to their benefits (How to assess the environmental impact of a large wildfire? How to assess the total benefits of all the use cases for a satellite?) Likely infeasible.

-->

# Research plan

The goal of the research plan presented in this section is to provide the theoretical foundation for addressing the research questions defined in @sec-research-questions.

## Methodology (research question 1)

In this section, the conceptual framework for assessing changes in surface albedo resulting from PV installations using satellite-derived remote sensing data is developed.

TBD: The following steps are required: data selection (area of interest and reference area), albedo measurement, data aggregation, ... (make this a figure)

### Albedo measurement and radiative forcing

This chapter outlines the principles and methods used for measuring surface albedo, describes its relationship with radiative forcing, and discussed how to assess the related environmental impact.

Albedo is defined as the ratio of reflected to incoming solar radiation: $\alpha =\frac{R_{reflected}}{R_{incoming}}$

It is a unitless quantity that can range between 0 for complete absorption to 1 for complete reflection. The albedo value of any location depends on the surface material, texture, color, and the angle of incoming solar radiation. Ground-based albedo can be measured using pyranometers or albedometers (e.g., mounted on towers) recording incoming and reflected shortwave radiation over a defined area. Although they are highly accurate, the ground-based measurements are limited in spatial coverage. Satellite remote sensing provides a spatially continuous means of estimating surface albedo, which will be further described in @sec-satellite-data-aquisition.

Radiative forcing (RF) is generally measured in measured in watts per square meter ($W m^{−2}$) and quantifies the change in the earth’s energy balance resulting from modifications to the incoming or outgoing radiation. There are many factors that can cause such a modification: Emission of green house gases such as CO₂ or CH₄, aerosols such as black carbon, land use changes and therefore albedo changes (focus of this work), and solar variability which are the natural fluctuations in the amount of solar radiation reaching the earth over time. The IPCC AR6 report by @IPCC_AR6_WGI_Chapter7_2021 assessed the contributions as presented in @tbl-ipcc below:

::: {#tbl-ipcc}
| Category                                | Radiative Forcing (2019 vs. 1750) |
| --------------------------------------- | --------------------------------- |
| Carbon dioxide CO₂                      | +2.16 W/m²                        |
| Methane CH₄                             | +0.54 W/m²                        |
| Nitrous oxide N₂O                       | +0.21 W/m²                        |
| Halogenated gases                       | +0.32 W/m²                        |
| Ozone O₃                                | +0.47 W/m²                        |
| Aerosols                                | −1.10 W/m²                        |
| Land use change related albedo change   | −0.15 W/m²                        |
| Contrails and aviation induced cirrus   | +0.05 W/m²                        |
| Solar variability                       | +0.01 W/m²                        |
| Gesamt                                  | ≈ +2.72 W/m²                      |

Table: IPCC AR6 report table 7.15
:::

Positive RF is the initial driver of climate change. It causes temperature rise in the atmosphere and on the earth surface (sea and land). Temperature rise causes ice-covered regions such as ice sheets, glaciers, and sea ice to melt. This is a positive feedback loop for further albedo changes, since bright surfaces are replaced by darker ones. Changes in surface albedo directly modify the shortwave component of the radiative balance. A reduction in albedo (e.g., replacing bright desert surface with dark PV panels) increases the absorption of solar energy, leading to positive radiative forcing (surface warming). Conversely, an increase in albedo contributes to negative radiative forcing (surface cooling). @tbl-ipcc contextualizes the radiative forcing resulting from overall land-use-change-related albedo changes, showing that, when considering all land-use changes (not just PV-related), the net effect of these albedo changes is cooling.

The radiative forcing impact $\Delta F$ caused by an albedo change $\Delta \alpha$ can be approximated as:

$$\Delta F = -S \cdot (1 - A) \cdot \Delta \alpha / 4$$

where the solar constant $S$ is equal to ~$1361 W m^{−2}$ and the planetary albedo $A$ amounts to ~$0.3$ (this is an empirically derived value from satellite measurements for the entire earth). The factor of ¼ accounts for the ratio of the earth’s cross-sectional area to its total surface area, since only the planet’s disk intercepts sunlight. This means that the intercepted energy must be averaged over the entire surface area of the earth to express the impact per unit area globally. Negative values of $\Delta F$ represent cooling (because of increased reflectivity), while positive values indicate warming (because of decreased reflectivity).

TBD: What is black-sky (direct) and white-sky (diffuse) albedo

### Satellite data aquisition {#sec-satellite-data-aquisition}

Many satellites provide relevant data (see @sec-satellite-data for a full overview). In this section, the most appropriate are identified. One of the main considerations is the data resolution (minimum pixel size available) required, which depends on the use case. It's also important to choose data that is in the public domain. Also relevant is the time frame for which the required data is available.

Some satellites, such as MODIS and VIIRS, provide direct albedo monitoring (e.g., MODIS MCD43A3, VIIRS VNP43). However, since the resolution from these satellites is generally coarse with 500 to 750 meters, the resulting data can only be applied for very large PV farms.

Other satellite types provide higher spatial resolution and therefore also support smaller PV sites. They employ multi-spectral sensors to record surface reflectance across different wavelengths (e.g., shortwave, visible, or near-infrared). The albedo can then be derived by applying weighted linear combinations of these reflectance values. Examples for this category are Landsat and Sentinel-2. Their spatial resolution is between 10 and 60 meters. Sentinel-2 data is available from 2015 onwards, and Landsat data from 1984 onwards (for use cases where longer history is required).

### Spatial selection and temporal data aggregation

The spatial areas of interest where the PV plant(s) are located will be defined based on the use case. All the data points that (completely and/or partly) cover the relevant area will be selected. This process can be supported with image recognition techniques (e.g. a deep learning model for detecting solar panels), or it can be based on defined location data.

Satellite-derived data generally contains significant inherent noise due to variable weather conditions and cloud cover, and also operational issues. Aggregating multiple observations spatially and temporally produces an average value, which reduces noise progressively as more data is combined. Consequently, the resulting estimates tend to be more stable for larger PV plants and over longer observation periods.

To understand the change in albedo there are two options for comparison, either against the same spatial area before the PV farm was installed, or same-sized reference area with a surface very similar to the original surface that was replaced by the PV plant. The latter is required for cases where no data from before the PV plant was installed can be found. It has the benefit that it allows to aggregate using the exact same temporal constraints (and likely operational issues if any), unlike in the before and after scenario. However there is also the downside that there might be other differences between the locations.

### Seasonality

Since seasonality such as temporal snow cover and vegetation dynamics in the location will play a role for many spatial areas of interest (including deserts), unless there are no seasons in the location, the temporal aggregation window should be at least one year. This means that only PV plants that existing for longer than that period can be evaluated instantly.

## Original surface related considerations (research question 2)

There are two aspects related to original surface: surface detection, and the retrieval of related albedo values per surface type.

Surface identification via satellite image is a solved problem. For identifying the original surface there are several relevant datasets such as @Zanaga2022_WorldCover2021v200, which is based on Sentinel data and provides the surface type for each 10x10 meter square globally. The surface categories are listed in table @tbl-esa. 

::: {#tbl-esa}
| Class                             | Description                                                                    |
| ----------------------------------| -------------------------------------------------------------------------------|
| Tree cover                        | Areas dominated by trees (≥10% cover), incl. plantations and flooded forests.  |
| Shrubland                         | Areas dominated by shrubs (<5 m tall) with ≥10% shrub cover.                   |
| Grassland                         | Areas dominated by herbaceous plants (≥10% cover); woody plants <10%.          |
| Cropland                          | Land where plants are sown or harvested at least once a year.                  |
| Built-up                          | Land covered by buildings, roads, and other man-made structures.               |
| Bare and sparse vegetation        | Lands with exposed soil, sand, or rocks, and ≤10% vegetative cover.            |
| Snow and ice                      | Areas persistently covered by snow or glaciers.                                |
| Permanent water bodies            | Lakes, reservoirs, and rivers mostly covered by water (>9 months/year).        |
| Herbaceous wetland                | Land dominated by herbaceous vegetation, permanently or regularly flooded.     |
| Mangroves                         | Salt-tolerant trees and plants in intertidal tropical zones.                   |
| Moss and lichen                   | Land covered by mosses and/or lichens, often in polar or high-altitude regions.|

Table: ESA WorldCover (10 m resolution global land cover map) categories
:::

### Albedo change by (original) surface type

@cescatti2012intercomparison provides a list of aggregated albedo values per surface type based on MODIS.

| Surface type                      | Description                                    | Mean yearly albedo (broadband 300-2800 nm) |
| --------------------------------- | ---------------------------------------------- | ------------------------------------------ |
| EBF (Evergreen Broadleaf Forest)  | Tropical evergreen broadleaf forests           | ~ 0.13                                     |
| ENF (Evergreen Needleleaf Forest) | Boreal/temperate evergreen needle‑leaf forests | ~ 0.11                                     |
| DBF (Deciduous Broadleaf Forest)  | Temperate deciduous broadleaf forests          | ~ 0.14                                     |
| MF (Mixed Forest)                 | Mixed broadleaf & needleleaf forests           | ~ 0.13                                     |
| WSA (Woody Savanna)               | Woody savanna landscapes                       | ~ 0.18                                     |
| SAV (Savanna)                     | Grass/savanna open woody vegetation            | ~ 0.21                                     |
| GRA (Grassland)                   | Natural grasslands                             | ~ 0.22                                     |
| CRO (Cropland)                    | Annual croplands                               | ~ 0.23                                     |

TBD: Need deserts, ice and snow 

## LCA integration (research question 3)

How can the satellite-derived data be incorporated into LCAs in a methodologically sound and credible manner, enabling its authoritative use in environmental impact assessments of solar energy systems? 

To include RF in an LCA, it is necessary to translate the RF value into a comparable impact metric, such as CO₂-equivalent emissions (CO₂eq).

### Trust in data sources

The hypothesis is that satellite-derived datasets from sources such as U.S. National Oceanic and Atmospheric Administration (NOAA) or European Organisation for the Exploitation of Meteorological Satellites (EUMETSAT) are considered reliable and scientifically validated. The expectation is that the given data quality should allow for quantifying aggregated albedo changes by original surface type and consequently support the incorporation of these effects into LCAs of PV systems.

### Dealing with data uncertainty

# Project plan for case study

Agri-PV installation at Campus Grüntal

In this section, a detailed research project plan for the suggested case study will be presented, together with project milestones and a time plan.

* Find out if we can get the relevant satellite data before and after

LCA format: Goal and scope, Functional unit definition, ...

## Project milestones and time plan

* Methodology definition

* Data acquisition

* Data aggregation

* Evaluation

* Validation

## Resources

* GeoAI Tutorial 13: Train a Deep Learning Model for Detecting Solar Panels
https://www.youtube.com/watch?v=_OmkNfcO7VU (https://opengeoai.org/)

<!--
Topics:


-->

# Appendix

## Overview: Satellite data for earth observation  {#sec-satellite-data}

This chapter provides an introduction to satellites that provide observational data of the earth for environmental monitoring. The many other existing use cases for satellites in communication, broadcasting, navigation, and for military purposes will not be discussed. 

::: {.table #tbl-methods caption="Methods for sensing"}

| Method                                 | Key feature           | Works at night | Cloud penetrating |
| -------------------------------------- | --------------------- | -------------- | ----------------- |
| Optical (incl. Near-Infrared, NIR)     | Reflects sunlight     | No             | No                |
| Thermal Infrared (IR)                  | Detects heat          | Yes            | No                |
| Synthetic Aperture Radar (SAR)         | Uses radar            | Yes            | Yes               |

:::

There are several different types of methods to sense the data: optical, thermal, and radar based as summarized in @tbl-methods. Optical methods detect sunlight reflected by clouds, land, and oceans, e.g., for red and blue visible light reflectance. Near-infrared (NIR) and infrared (IR) is invisible to the human eye. NIR is strongly reflected by vegetation, and absorbed by water. Therefore, NIR based methods make land cover, plant health, and boundaries between land and water easy to detect. IR detects thermal radiation, i.e. heat, emitted from the earth and atmosphere at day and night. This is useful for observation of temperature and moisture or dryness as well as atmospheric gaseous water vapor. Synthetic Aperture Radar (SAR) is an active method that works at night and through clouds (unlike the other methods). It detects surface structure and moisture.

At a high level, satellites can be categorized based on their orbital types, which determine their position and altitude, and consequently coverage and purpose: 

1. Low Earth Orbit (LEO) satellites orbit at altitudes between 160 and 2.000 kilometers. They are known for their high resolution data. A subset of them, polar orbits, pass over the earth's poles and provide global coverage as the planet rotates beneath them. Another subset is sun-synchronous orbits, which maintain a consistent position relative to the sun, allowing satellites to observe the earth under similar lighting conditions with each pass. 

1. Medium Earth Orbit (MEO) satellites operate at altitudes ranging above 2.000 and below 35.000 kilometers. They are typically used for navigation services such as devised based on Assisted Global Navigation Satellite Systems as defined in [@3gppagnss], which rely on acquiring and decoding satellite signals to determine their position. 

1. Geostationary Earth Orbit (GEO) satellites are located above the equator at 35.786 kilometers, which matches the earth's rotation period, to provide continuous observation of a fixed region of the earth. They are known for providing low resolution data with high update frequency. The data provided is often used for weather and broad climate monitoring.

Each of these orbital satellite types serves different purposes. The satellite orbital types most common for earth observation are LEO and GEO satellites. In the following, an overview of available public domain and commercial observational satellite data of these types that could potentially be relevant for LCA is provided.

### Geostationary Earth Orbit (GEO) satellites

Observational Geostationary Earth Orbit satellites provide continuous, real-time monitoring of atmospheric conditions, cloud cover, sea surface temperatures, and solar radiation over large fixed regions. They have lower spatial resolution compared to LEO satellites, but this is being compensated by providing high temporal resolution. @tbl-geo-satellites provides an overview of the existing GEO satellites, their operators, the regions covered, the type of access and, if relevant, the license that the data is available under. 

::: {.table #tbl-geo-satellites caption="GEO satellites overview"}

| Satellite / Series                             | Operator / Agency    | Region Covered                 | Licensing                                     |
| ---------------------------------------------- | -------------------- | ------------------------------ |---------------------------------------------- |
| GOES series (GOES-16, GOES-17, GOES-18)        | NOAA (USA)           | Americas                       | Most data available under NOAA's data policy  |
| Meteosat (MSG and MTG series)                  | EUMETSAT (Europe)    | Europe, Africa, Atlantic Ocean | Open access under EUMETSAT’s data policy      |
| Himawari series (8 and 9)                      | JMA (Japan)          | Asia-Pacific region            | Open access for research and public use       |
| INSAT/GSAT series (INSAT-3D, INSAT-3DR)        | ISRO (India)         | Indian subcontinent            | Limited public access                         |
| Fengyun series (FY-2, FY-4)                    | CMA (China)          | Asia-Pacific region            | Restricted access for partners                |
| Electro-L series                               | Russian Space Agency | Russia, Europe, parts of Asia  | Limited public access                         |

:::

The three satellite series where data that is accessible under open licenses offer data delivery frequencies between 5 and 15 minutes for full images. They provide similar imaging capabilities: 16 spectral ranges of wavelengths, called bands or channels, collected by the satellite sensor as discrete portions of the electromagnetic spectrum. Each series provides comparable numbers of optical, near-infrared and infrared channels.

They support rapid scan modes for their regions of focus with data delivery frequencies between 30 seconds and 5 minutes. These are used for detecting fast-changing weather and environmental events such as storms, tornadoes, wildfires and volcanic eruptions, and for short-term weather forecasting (called now-casting). 

To summarize, GEO satellites for earth observation are most helpful for high-frequency monitoring of large-scale land and ocean processes.

### Low Earth Orbit (LEO) satellites

Far more LEO satellites for earth observation than GEO satellites exist: around 35 GEO satellites compared to around 1000 LEO satellites. @tbl-leo-satellites provides a non-exhaustive listing of the most relevant providers together with the resolution and revisit frequency of the data provided. Note that some providers have more than one satellite on offer. In these cases only the one with the highest resolution and revisit frequency is listed. The newest satellites are Biomass from ESA for forest biomass and carbon content monitoring, and FireSat and OroraTech for wildfire detection. The (*) sign indicates future plans.

::: {.table #tbl-leo-satellites caption="LEO satellites overview"}

| Satellite / provider        | Access     | Resolution                    | Revisit Frequency          |
| --------------------------- | -----------| ----------------------------- | -------------------------- |
| Landsat 8 & 9               | open       | 15 – 30 m multispectral       | 8 days (combined)          |
| Sentinel-1 (A & B/C)        | open       | 5 – 20 m SAR                  | 6 days (combined)          |
| Sentinel-2 (A, B & C)       | open       | 10 – 60 m multispectral       | 5 days (combined)          |
| MODIS (Terra, Aqua)         | open       | 250 m – 1 km multispectral    | Daily                      |
| VIIRS                       | open       | 375 m – 750 m multispectral   | Daily                      |
| Biomass                     | open (*)   | 10 m P-band SAR               | Up to 16 orbits/day        |
| Planet Labs                 | commercial | 3 – 5 m optical               | Daily                      |
| Maxar WorldView             | commercial | 30 – 50 cm optical            | Up to 15 orbits/day       |
| Airbus                      | commercial | 30 cm optical                 | 1–3 days                   |
| Iceye                       | commercial | 0.5 m SAR                     | Daily to sub-daily         |
| Capella Space               | commercial | 0.5 m SAR                     | Daily to sub-daily         |
| GHGSat                      | commercial | 25 m                          | Variable                   |
| FireSat                     | commercial | 5 m thermal IR                | 30 minutes (*)             |
| OroraTech                   | commercial | Variable thermal IR           | 30 minutes (*)             |

:::

<!-- 
| RapidEye                    | commercial | 5 m multispectral             | Daily                      | medium-resolution multispectral                             |
| Deimos-1 & 2                | commercial | 22 m (D1), 75 cm (D2) optical | 1–3 days                   | commercial EO satellites                                    |
| Satellogic                  | commercial | <1 m multispectral            | Daily                      | medium-resolution multispectral                             |
| BlackSky                    | commercial | \~90 cm optical               | Multiple times daily       | rapid revisit, analytics platform                           |
-->

To summarize, LEO satellites play a crucial role in earth observation, particularly for high-resolution and frequent monitoring. The revisit frequency is primarily determined by the size of the satellite constellation. Larger constellations, such as those with over 100 satellites, can achieve revisit frequencies approaching those of geostationary systems. 

### Data availability for research purposes

While a few public providers offer open-access data with comparatively low resolution, many different commercial options for very high resolution data are on the market. The pricing models of the commercial options depend on the amount of data required and the use case, and are available upon request. Limited opportunities to access the commercial data under a research license exist. The NASA-led Commercial Satellite Data Acquisition Program @csda_nasa provides access to some of the data for research purposes, most notably for the Maxar WorldView data. It has been used in a number of scientific articles as assessed by @zhao2022overview who conducted a literature study of scientific articles referencing EO satellite missions and found that their number is exponentially growing, and while some cite commercial sources, most of the work is based on the freely available data. In this project, the focus will be on data that is available for research purposes.

# References
