---
title: "Leftovers"
format: html
editor: visual
---

## Quarto

Dieser Schweizer Bauer hat ein Wassersystem für die Zukunft gebaut
https://www.tagesanzeiger.ch/katzhof-richenthal-der-klimaresistenteste-hof-der-schweiz-526267449775

Contrail Cirrus Climate Impact: From Radiative Forcing to Surface Temperature Change
https://journals.ametsoc.org/view/journals/clim/38/8/JCLI-D-24-0245.1.pdf

Evidence for climate change in the satellite cloud record
https://www.nature.com/articles/nature18273
Clouds play a huge role in Earth's temperature by both reflecting sunlight back into space (a cooling effect) and trapping heat from the ground (a warming effect). How clouds will change due to global warming has been one of the biggest questions in climate science. Climate models and real-world observations didn't agree on how clouds have changed in recent decades. This is largely because the satellites used to monitor clouds were built for short-term weather forecasting, not for tracking subtle, long-term climate changes. The data from these older systems needed to be carefully corrected to be reliable. This study successfully corrected several independent satellite records from the 1980s to the 2000s. After correction, the data revealed large-scale cloud changes that match the predictions made by climate models. Both the real-world data and the computer models show the same patterns: Storm tracks are moving away from the equator and towards the poles. Subtropical dry zones are expanding. The highest cloud tops are getting even higher. The main causes for these changes are rising greenhouse gas concentrations and the planet warming up after the cooling effects of past volcanic eruptions. This research shows that the cloud changes long predicted by climate models are actually happening now.

Earth’s long-term climate stabilized by clouds
https://www.nature.com/articles/s41561-021-00691-7?fromPaywallRec=true
Billions of years ago, the Sun was much dimmer than it is today.Logically, Earth should have been a frozen ice ball, but evidence shows it had liquid water. This mystery is called the "faint young Sun problem."
For a long time, scientists thought the solution was a much stronger greenhouse effect. The idea was that early Earth's atmosphere was filled with extra greenhouse gases (like CO₂), which trapped the Sun's faint heat and kept the planet warm enough for liquid water.
This study suggests a different key factor: clouds.
Researchers used climate models to look back in time. They found that with a dimmer sun and more CO₂, early Earth had far fewer low-level clouds than it does today.
Fewer clouds meant less sunlight was reflected away from the planet's surface. Think of it like a dark t-shirt absorbing more sunlight than a white one. By absorbing more of the Sun's faint energy, the planet stayed warm. This cloud effect was incredibly powerful, providing about 40% of the warming needed to solve the problem.

Groups:
https://en.wikipedia.org/wiki/Space_for_Climate_Observatory

Journals:
International Journal of Applied Earth Observation and Geoinformation

People:
Remote sensing agriculture: Bruno Basso
https://scholar.google.com/citations?user=EItklH0AAAAJ&hl=en

Problems:
Amazon often full with clouds, gets exploited by loggers

Use cases: 
forest https://scholar.google.com/scholar?hl=en&as_sdt=0,5&qsp=2&q=forest+loss+life+cycle+assessment&qst=bl
water (?) 
contrails (??)

## Environmental impact of satellites

(2024) A life cycle assessment study of European Space Agency's space tracking terminal
https://pubs.rsc.org/en/content/articlehtml/2024/va/d4va00070f

(2024) Life Cycle Assessment for Varying Design Lifetime Mission Architecture for Low Earth Orbit Constellation Satellites with Starlink as a Case Study
https://www.researchgate.net/publication/384634078_Life_Cycle_Assessment_for_Varying_Design_Lifetime_Mission_Architecture_for_Low_Earth_Orbit_Constellation_Satellites_with_Starlink_as_a_Case_Study

(2025) Greenhouse Gas (GHG) Emissions Poised to Rocket: Modeling the Environmental Impact of LEO Satellite Constellations
https://arxiv.org/abs/2504.15291

Quantifying the Environmental Impacts of Manufacturing Low Earth Orbit (LEO) Satellite Constellations 
https://www.mdpi.com/2071-1050/16/21/9431

Estimates for environmental impact of satellites:
https://pre-sustainability.com/customer-cases/environmental-impacts-satellite-mission/


# Tools and datasets

In the following, datasets and tools that could be valuable as input for LCAs are assessed.

## AlphaEarth Foundations

An embedding field model for accurate and efficient global mapping from sparse label data

https://deepmind.google/discover/blog/alphaearth-foundations-helps-map-our-planet-in-unprecedented-detail/

https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_SATELLITE_EMBEDDING_V1_ANNUAL?hl=de

@brown2025alphaearthfoundationsembeddingfield

10x10 meter

Unprecedented volumes of Earth observation data are continually collected around the world, but high-quality labels remain scarce given the effort required to make physical measurements and observations. This has led to considerable investment in bespoke modeling efforts translating sparse labels into maps. Here we introduce AlphaEarth Foundations, an embedding field model yielding a highly general, geospatial representation that assimilates spatial, temporal, and measurement contexts across multiple sources, enabling accurate and efficient production of maps and monitoring systems from local to global scales. The embeddings generated by AlphaEarth Foundations are the only to consistently outperform all previous featurization approaches tested on a diverse set of mapping evaluations without re-training. We will release a dataset of global, annual, analysis-ready embedding field layers from 2017 through 2024. 

https://developers.google.com/earth-engine/datasets/catalog/GOOGLE_SATELLITE_EMBEDDING_V1_ANNUAL?hl=de#description
https://medium.com/google-earth/ai-powered-pixels-introducing-googles-satellite-embedding-dataset-31744c1f4650

## Planetary Computer

The Planetary Computer combines a multi-petabyte catalog of global environmental data with intuitive APIs, a flexible scientific environment that allows users to answer global questions about that data, and applications that put those answers in the hands of conservation stakeholders.

https://planetarycomputer.microsoft.com/

## GlobalBuildingAtlas

https://github.com/zhu-xlab/GlobalBuildingAtlas?tab=readme-ov-file

## Cropland Data Layer

Agriculture: The Cropland Data Layer (CDL) is a dataset provided by the U.S. Department of Agriculture's National Agricultural Statistics Service (NASS) that provides information about crop types across the United States.

## Forest baseline

(2025) Natural forests of the world-a 2020 baseline for deforestation and degradation monitoring @neumann2025natural 
Forest stuff PhD student: https://github.com/SherryJYC

## MethaneSAT

https://developers.google.com/earth-engine/datasets/catalog/projects_edf-methanesat-ee_assets_public-preview_L4area?hl=de

https://showcase.earthengine.app/view/methanesat

https://blog.google/outreach-initiatives/sustainability/how-satellites-algorithms-and-ai-can-help-map-and-trace-methane-sources/

* Plan some kind of LCA project based on Oil and Gas Infrastructure Mapping (OGIM) / MethaneSAT: https://developers.google.com/earth-engine/datasets/catalog/EDF_OGIM_current?hl=de (also see ESU-services: https://esu-services.ch/fileadmin/download/jungbluth-2022-oilgas-FSLCI-20220914.pdf) Fokus auf spezifische Commodity (Erdgas, Rohöl oder Fracking)

   * MethaneSAT data: https://portal.methanesat.org/en/emissions-map?view-latitude=29.97421&view-longitude=22.15457&view-zoom=3.48&date=2025-06-30&platform=MethaneSAT&product=l4&color-scale=msat_warm_default
   * https://www.methanesat.org/project-updates/new-methane-emissions-insights-will-continue-methanesat-data-catalogue-processed

* Plan some kind of LCA project based on AlphaEarth Foundations (could use data within Google Earth Engine for analysis and visualization for research or educational use. Downloading, redistributing, or incorporating the data into other software is not permitted.)
    * Landwirtschaft mit Fokus auf eine spezifische Commodity (Kaffee, Soja, Kakao, Reis, oder andere)
    * Mining mit Fokus auf spezifische Commodity (Kupfer, Gold, Nickel, Silber, Aluminium, Eisen, Kohle, Lithium, Uran)
    * Energiesektor mit Fokus auf spezifische Kraftwerke (Kohle, Gas, Wasserkraft, Windkraft oder PV)
    
* Plan a project to use ESA Biomass satellite for LCA for forest loss (data not yet in the public domain)

* LCA to assess the environmental impact of satellites in comparison to their benefits (How to assess the environmental impact of a large wildfire? How to assess the total benefits of all the use cases for a satellite?) Likely infeasible.

* GeoAI Tutorial 13: Train a Deep Learning Model for Detecting Solar Panels
https://www.youtube.com/watch?v=_OmkNfcO7VU (https://opengeoai.org/)
